import type { State } from "./types";

const now = Date.now();
const min = 60_000;
const hour = 60 * min;
const day = 24 * hour;

export const DEFAULT_TEAM = "siki84sak-3148s-projects";
export const CURRENT_USER = "siki84sak";

export const seed: State = {
  teams: [{ slug: DEFAULT_TEAM, name: "siki84sak's projects", plan: "Hobby" }],
  projects: [
    {
      id: "prj_ebay",
      name: "v0-ebay-clone",
      teamSlug: DEFAULT_TEAM,
      framework: "Next.js",
      repo: "siki84/v0-ebay-clone",
      productionBranch: "main",
      createdAt: now - 12 * day,
    },
    {
      id: "prj_portfolio",
      name: "portfolio",
      teamSlug: DEFAULT_TEAM,
      framework: "Next.js",
      repo: "siki84/portfolio",
      productionBranch: "main",
      createdAt: now - 40 * day,
    },
    {
      id: "prj_docs",
      name: "docs-site",
      teamSlug: DEFAULT_TEAM,
      framework: "Astro",
      repo: "siki84/docs-site",
      productionBranch: "main",
      createdAt: now - 90 * day,
    },
  ],
  domains: [
    {
      id: "dom_1",
      projectId: "prj_ebay",
      name: "v0-ebay-clone.vercel.app",
      verified: true,
      redirect: null,
      gitBranch: null,
      createdAt: now - 12 * day,
    },
    {
      id: "dom_2",
      projectId: "prj_ebay",
      name: "v0-ebay-clone-git-main-siki84sak-3148s-projects.vercel.app",
      verified: true,
      redirect: null,
      gitBranch: "main",
      createdAt: now - 12 * day,
    },
    {
      id: "dom_3",
      projectId: "prj_portfolio",
      name: "portfolio-siki84.vercel.app",
      verified: true,
      redirect: null,
      gitBranch: null,
      createdAt: now - 40 * day,
    },
    {
      id: "dom_4",
      projectId: "prj_docs",
      name: "docs-site-siki84.vercel.app",
      verified: true,
      redirect: null,
      gitBranch: null,
      createdAt: now - 90 * day,
    },
  ],
  deployments: [
    {
      id: "dpl_a1",
      projectId: "prj_ebay",
      url: "v0-ebay-clone-8f3k2la1q-siki84sak-3148s-projects.vercel.app",
      status: "Ready",
      environment: "Production",
      branch: "main",
      commitSha: "4e1c9ab",
      commitMessage: "Add product detail page and cart drawer",
      author: CURRENT_USER,
      createdAt: now - 2 * hour,
      durationSec: 41,
      current: true,
    },
    {
      id: "dpl_a2",
      projectId: "prj_ebay",
      url: "v0-ebay-clone-p02mzk7xr-siki84sak-3148s-projects.vercel.app",
      status: "Ready",
      environment: "Preview",
      branch: "feat/search",
      commitSha: "b72d013",
      commitMessage: "Search with filters and sort",
      author: CURRENT_USER,
      createdAt: now - 5 * hour,
      durationSec: 38,
    },
    {
      id: "dpl_a3",
      projectId: "prj_ebay",
      url: "v0-ebay-clone-c9qwe81bn-siki84sak-3148s-projects.vercel.app",
      status: "Error",
      environment: "Preview",
      branch: "feat/checkout",
      commitSha: "19aa7f2",
      commitMessage: "WIP checkout flow",
      author: CURRENT_USER,
      createdAt: now - 1 * day,
      durationSec: 17,
    },
    {
      id: "dpl_a4",
      projectId: "prj_ebay",
      url: "v0-ebay-clone-3jd8s0wpe-siki84sak-3148s-projects.vercel.app",
      status: "Ready",
      environment: "Production",
      branch: "main",
      commitSha: "0d5e6c1",
      commitMessage: "Initial commit from v0",
      author: CURRENT_USER,
      createdAt: now - 12 * day,
      durationSec: 52,
    },
    {
      id: "dpl_b1",
      projectId: "prj_portfolio",
      url: "portfolio-7hd72kdl0-siki84sak-3148s-projects.vercel.app",
      status: "Ready",
      environment: "Production",
      branch: "main",
      commitSha: "aa83e10",
      commitMessage: "Update projects section",
      author: CURRENT_USER,
      createdAt: now - 3 * day,
      durationSec: 29,
      current: true,
    },
    {
      id: "dpl_c1",
      projectId: "prj_docs",
      url: "docs-site-k2l0ap9qe-siki84sak-3148s-projects.vercel.app",
      status: "Ready",
      environment: "Production",
      branch: "main",
      commitSha: "7f0b2c4",
      commitMessage: "Fix broken links",
      author: CURRENT_USER,
      createdAt: now - 20 * day,
      durationSec: 33,
      current: true,
    },
  ],
  envVars: [
    {
      id: "env_1",
      projectId: "prj_ebay",
      key: "NEXT_PUBLIC_API_URL",
      value: "https://api.example.com",
      targets: ["Production", "Preview", "Development"],
      createdAt: now - 12 * day,
    },
    {
      id: "env_2",
      projectId: "prj_ebay",
      key: "DATABASE_URL",
      value: "postgres://user:secret@db.example.com:5432/shop",
      targets: ["Production"],
      createdAt: now - 10 * day,
    },
  ],
};
